# Generated by Django 5.0.3 on 2024-03-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
