# Generated by Django 5.0.3 on 2024-03-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
